name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional but recommended for multi-arch & better compatibility
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kstrycharz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the image from the repo root (change context/file if needed)
      - name: Build and push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            kstrycharz/lolminer-container:latest
            kstrycharz/lolminer-container:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
